### ISSUE TITLE
The last releases don't show the options (Legende) at the wanted location * not really fixed in 1.4.0 *

### ISSUE THREAD

**Issue by uelpenich** [ioBroker/ioBroker.echarts#250]
**Describe the bug**  
The last releases don't show the options (Legende) at the wanted location

**To Reproduce**  
define the location of the option (Legende) other than "Oben, Mitte"

**Expected behavior**  
the location of the option (Legende) should be displayd at the defined place (this is adapter version 1.2.1):
![grafik](https://user-images.githubusercontent.com/63613798/217660206-7a175828-7726-410a-8809-acf435e8f2d2.png)

**Screenshots & Logfiles**  
This is adapter version 1.3.4:
![grafik](https://user-images.githubusercontent.com/63613798/217655747-214860c2-684e-4cfd-953f-2a8c5a931d88.png)

**Versions:**  
 - Adapter version:  1.3.0 . . 1.3.4
 - JS-Controller version: v16.18.1
 - Node version: v16.18.1
 - Operating system: raspberry pi

**Additional context**

**Comment by joergeli** [comment]
Same behavior.
No reaction on **any** legends menu item I select.
Adapter version: 1.3.4

**Comment by GermanBluefox** [comment]
fixed in 1.3.5.

**Comment by uelpenich** [comment]
Sorry, the problem is not really fixed. 
Versions:

    Adapter version: 1.3.0 . . 1.3.4
    JS-Controller version: v16.18.1
    Node version: v16.18.1
    Operating system: raspberry pi

I notice a timing problem for charts with a lot of data sources (10 sources in this example). 
[10 sources echart.txt](https://github.com/ioBroker/ioBroker.echarts/files/10725770/10.sources.echart.txt)

What happens?
When I want to look at a diagram in the admin echart edit environment, or in a seperate window, it starts with a quiet empty view like this:
![grafik](https://user-images.githubusercontent.com/63613798/218553707-342a91ad-3682-421f-ac96-2af97d605993.png)
After a long time (~25 seconds) I get the expected charts:
![grafik](https://user-images.githubusercontent.com/63613798/218554001-023b25a0-ca82-49ce-a64f-9bdc349b064f.png)
The firefox network analysis shows this log:
![grafik](https://user-images.githubusercontent.com/63613798/218554295-2894b7b9-02cc-46d3-85bd-609e1cb76d8a.png)
Every 10 to 20 seconds the view changes between these two displays. 

The Firefox debugger shows some not completely transfered data:
[complete theme.txt](https://github.com/ioBroker/ioBroker.echarts/files/10725674/complete.theme.txt)

[uncomplete theme.txt](https://github.com/ioBroker/ioBroker.echarts/files/10725675/uncomplete.theme.txt)

Other errors are:
* Layout-Darstellung wurde erzwungen, bevor die Seite vollständig geladen war. Falls Stylesheet noch nicht geladen sind, kann dies zu einem kurzzeitigen Darstellung des Inhalts ohne Formatierung führen.
* Received unknown message: "chartReady"
* Cannot read : The id is empty! Please provide a valid id.
* TypeError: t is null
* Cannot apply options: {"theme":"roma" . . .
* Uncaught TypeError: t is null

PS: google chrome shows the same behaviour. 

Do you need any further information for debuggin? Many thanks for your work. 
Werner

**Comment by GermanBluefox** [comment]
Exactly these errors are interesting:
```
Other errors are:

Layout-Darstellung wurde erzwungen, bevor die Seite vollständig geladen war. Falls Stylesheet noch nicht geladen sind, kann dies zu einem kurzzeitigen Darstellung des Inhalts ohne Formatierung führen.
Received unknown message: "chartReady"
Cannot read : The id is empty! Please provide a valid id.
TypeError: t is null
Cannot apply options: {"theme":"roma" . . .
Uncaught TypeError: t is null
```
Please provide the full browser console output (errors especially)

**Comment by uelpenich** [comment]
Full browser console output Firefox: 
[console-export-2023-2-14_14-23-55.txt](https://github.com/ioBroker/ioBroker.echarts/files/10734051/console-export-2023-2-14_14-23-55.txt)
Browser Firefox console output (errors especially)
[console-export-2023-2-14_16-35-0 Errors only.txt](https://github.com/ioBroker/ioBroker.echarts/files/10734096/console-export-2023-2-14_16-35-0.Errors.only.txt)

PS: The ioBroker App on a iPhone shows the same behaviour. The change from the empty view to the expected charts vice versa occurs syncronously to Windows Firefox.

**Comment by GermanBluefox** [comment]
> Full browser console output Firefox: [console-export-2023-2-14_14-23-55.txt](https://github.com/ioBroker/ioBroker.echarts/files/10734051/console-export-2023-2-14_14-23-55.txt) Browser Firefox console output (errors especially) [console-export-2023-2-14_16-35-0 Errors only.txt](https://github.com/ioBroker/ioBroker.echarts/files/10734096/console-export-2023-2-14_16-35-0.Errors.only.txt)
> 

All these errors are produced by firefox extensions and not by echarts. The only relevant error is this one 
![image](https://user-images.githubusercontent.com/4582016/219082830-eba368d6-a88c-4a23-95fa-f291d58c3360.png)

but it must be observed with at start opened browser console. If you open the console in the middle of the process no mapping information is loaded and I don't know which code line produces an error.

Please open first browser console, then F5 and then reproduce error, that is relevant to echarts and not to firefox extension. That will help enormous.

**Comment by uelpenich** [comment]
>> All these errors are produced by firefox extensions and not by echarts. 
For my previous tests I used Windows 11, and the actual firefos with two extensions: KeePassXC Browser and Video DownloadHelper.

To avoid any OS and firefos extension problems I did a test on a actual empty Ubuntu 22.04.1 LTS system. My Ubuntu Firefox 108.0.1 (64 Bit) is as installed without any extension. This is my test sequence:
* start Firefox, the default Firefox start page appears
* start the browser console in multiprocess mode
* start iobroker page with "iobroker.local:8081/#tab-echarts"
The result is the same behavior as described in https://github.com/ioBroker/ioBroker.echarts/issues/250#issuecomment-1428565161

This is the Ubuntu Firefox console log from the beginning to the "quiet empty view" and ends with the "expected charts",
then F5 with a new cycle of the "quiet empty view" and the "expected charts"
[Ubuntu Firefox console-export-2023-2-15_20-25-10.txt](https://github.com/ioBroker/ioBroker.echarts/files/10746658/Ubuntu.Firefox.console-export-2023-2-15_20-25-10.txt)

I hope this helps.

**Comment by uelpenich** [comment]
**Important additional info:**
The problem occurs only on charts having a data source of type boolean. 
If I remove the data source of type boolean the chart is drawn as expected. 

==> it lookes like the automatic type conversion boolean to integer doesn't work anymore (as pointed out at iobroker.viessmann adapter)

PS: for history I use Mariadb database. for history data there are 3 distinguished tabels used for numbers, boolean and strings. What happens if I try to use a data source of type string?

**Comment by GermanBluefox** [comment]
I still cannot reproduce it:
![image](https://user-images.githubusercontent.com/4582016/219314820-ff18fd33-fa97-480d-bc95-eae96e2b6563.png)

I guess that the problem is reproducible in chrome too?
Please check it with 1.4.3 (from npm and not from github)

**Comment by uelpenich** [comment]
We get closer. The problem occurs only if you choose **Options - display values**. 
If you don't display values the chart is displayed correctly.
![grafik](https://user-images.githubusercontent.com/63613798/219360150-929bb768-c0a2-4946-9e87-faf10cba0c10.png)

**Comment by GermanBluefox** [comment]
Fixed in 1.4.4

**Comment by uelpenich** [comment]
I tried 1.4.5, it is much better, but a bug is still there. 

The browser console doesn't show errors anymore. 

The first displayed chart looks good but the dimension of the boolean value [B] is missing. 
![grafik](https://user-images.githubusercontent.com/63613798/219430241-250fdaf9-ffe1-4296-9813-70067994c36a.png)

After the **auto update time** the boolean value is not displayed anymore. 
In **hoover details** the dimension is present. 
![grafik](https://user-images.githubusercontent.com/63613798/219430688-d3c73175-c5fa-4848-a08a-6230c9dc1377.png)

**Comment by GermanBluefox** [comment]
Sorry, but the boolean value does not have units. I will remove it from settings

**Comment by uelpenich** [comment]
_After the auto update time the boolean value is not displayed anymore._ 
EDIT:  only value [FALSE] is not displayed anymore. Value [TRUE] is always displayed correctly.
